version: "3"
services:
  app:
    build:
      context: .
      target: builder
    ports:
      - "5000:5000"
    expose:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start